// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17NxhcEyITsMD2muUFo00U0CZ-79R1B0',
    appId: '1:762354888186:web:6836e63d3778a980d10843',
    messagingSenderId: '762354888186',
    projectId: 'chatapplicationwithflutt-4e73c',
    authDomain: 'chatapplicationwithflutt-4e73c.firebaseapp.com',
    storageBucket: 'chatapplicationwithflutt-4e73c.appspot.com',
    measurementId: 'G-JS68VJQ1T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkIn4kdAO6WSN7mKjjHnCiZ7HIWKyDM8',
    appId: '1:762354888186:android:711fb6e4a780bcaad10843',
    messagingSenderId: '762354888186',
    projectId: 'chatapplicationwithflutt-4e73c',
    storageBucket: 'chatapplicationwithflutt-4e73c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttL4B2XC2oV5GbQDGjETI3mcGCordfUU',
    appId: '1:762354888186:ios:e16ff2f5086b6444d10843',
    messagingSenderId: '762354888186',
    projectId: 'chatapplicationwithflutt-4e73c',
    storageBucket: 'chatapplicationwithflutt-4e73c.appspot.com',
    iosClientId: '762354888186-vmjedef7imko2cu9kjkokhh742hbg9tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
